global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Amazon.DynamoDBv2.DataModel;
global using Amazon.DynamoDBv2;
global using Amazon.DynamoDBv2.DocumentModel;
global using Amazon.Lambda.APIGatewayEvents;
global using Amazon.Lambda.Core;
global using Microsoft.Extensions.Options;